pipeline:
  workspace_root: .
  input_videos: C:\test
  step1_wav: workspace\01_wav
  step2_separated: workspace\02_separated
  step3_srt_raw: workspace\03_srt_raw
  step4_srt_translated: workspace\04_srt_translated
  step5_video_subbed: workspace\05_video_subbed
  step6_final: D:\t\PROJECT_ROOT\output
  step6_voices_cache: workspace\06_voices
  done: done
  failed: failed
ffmpeg_bin: C:/ffmpeg/ffmpeg.exe
step1:
  sample_rate: 16000
  channels: 1
step2:
  model: htdemucs
  device: cuda
  jobs: 1
  two_stems: true
  shifts: 2
  output_float32: false
step3:
  srt_source: image
  model_size: large-v2
  device: cuda
  language: zh
  cpu_threads: 1
  image_frame_interval: 0.5
  image_step_frames: 10
  image_ocr_lang: ch
  image_use_gpu: true
  similarity_threshold: 0.7
  image_min_duration_ms: 250
  image_confidence_threshold: 0.5
step4:
  model_name: gemini-2.5-flash
  source_lang: zh-CN
  target_lang: vi
  gemini_api_keys: []
  max_lines_per_chunk: 250
step5:
  ocr_lang: ch
  roi_y_start: 0.0
  roi_y_end: 1.0
  font_path: ''
  font_size: 45
  max_words_per_line: 10
  text_color:
  - 255
  - 255
  - 0
  - 255
  outline_color:
  - 0
  - 0
  - 0
  - 255
step6:
  tts_lang: vi
  bg_volume: -12.0
  pitch_factor: 1.0
  tts_volume: 1.4
  min_words_for_tts: 0
  speedup_when_short: 1.5
  original_voice_volume: 0.2
